eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

define:
  druid:
    username: admin
    password: admin123     #数据库监控  druid 配置
  mysql:
    write:
      url: jdbc:mysql://localhost:3306/ps_dev?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: admin123
    read1:
      url: jdbc:mysql://localhost:3306/ps_dev?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: admin123
  paging:
    defaultSize: 15      #默认分页大小
    defaultNum: 1

#admin 监控配置信息
security:
  user:
    password: admin123
    name: admin
