spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${define.mysql.write.url}
    username: ${define.mysql.write.username}
    password: ${define.mysql.write.password}
  jpa:
    hibernate:
      ddl-auto: validate