spring:
  cloud:
    client:
      ipAddress: localhost
    config:
      server:
        git:
          uri: https://github.com/yanglangfei/base
          search-paths: /config/config
          basedir: /config
      profile: dev
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 47.98.168.231
    port: 5672
    username: admin
    password: admin123
logging:
  file: D:\Logs\com\config.log
  level:
    com.naju: debug
hystrix.stream.dashboard.intervalInMilliseconds: 5000

#security:
 # user:
  #  password: admin123
   # name: admin





