server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false


management:
  security:
    enabled: false
security:
  user:
    name: admin
    password: admin123



